/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_VDSOCLOCKSOURCE_H
#define __ASM_VDSOCLOCKSOURCE_H

enum vdso_arch_clockmode {
	
	VDSO_CLOCKMODE_NONE,
	
	VDSO_CLOCKMODE_ARCHTIMER,
	
	VDSO_CLOCKMODE_ARCHTIMER_NOCOMPAT,
};

#endif
